@startuml Hello_World
skinparam Style strictuml
Actor Wojtek #lightGreen
Wojtek ->> A
A -> B : Hello world
B -> A : Hi
A <-- B : OK
alt "dupa"
A -> C : siemka
end
C -> B : return
B -> A : end
@enduml